export default [
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '3',
    categoryDescription: 'ACTIF',
    subCategory: '300',
    subCategoryDescription: 'Actif circulant ',
    group: '3000',
    groupDescription: 'Renovation Fund ',
    blppAccountMapping: '251110',
    account: '640010',
    accountDescription: 'Yearly Contribution'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '3',
    categoryDescription: 'ACTIF',
    subCategory: '300',
    subCategoryDescription: 'Actif circulant ',
    group: '3000',
    groupDescription: 'Renovation Fund ',
    blppAccountMapping: '251110',
    account: '640010',
    accountDescription: 'Yearly Contribution'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '1',
    categoryDescription: 'Produit',
    subCategory: '100',
    subCategoryDescription: 'Produits',
    group: '1000',
    groupDescription: 'Revenue ',
    blppAccountMapping: '310000',
    account: '300000',
    accountDescription: 'Rents collected',
    accountIsPmVisible: 'true',
    accountIsRentAmount: 'true',
    accountIsRevenue: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '1',
    categoryDescription: 'Produit',
    subCategory: '100',
    subCategoryDescription: 'Produits ',
    group: '1000',
    groupDescription: 'Revenue ',
    accountDescription: 'Rents collected',
    accountIsPmVisible: 'true',
    accountIsRentAmount: 'true',
    accountIsRevenue: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '1',
    categoryDescription: 'Produit',
    subCategory: '100',
    subCategoryDescription: 'Produits',
    group: '1000',
    groupDescription: 'Revenue ',
    accountDescription: 'Rents collected',
    accountIsPmVisible: 'true',
    accountIsRentAmount: 'true',
    accountIsRevenue: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '1',
    categoryDescription: 'Produit',
    subCategory: '100',
    subCategoryDescription: 'Produits ',
    group: '1000',
    groupDescription: 'Revenue ',
    blppAccountMapping: '310000',
    account: '310000',
    accountDescription: 'Rents collected',
    accountIsPmVisible: 'true',
    accountIsRentAmount: 'true',
    accountIsRevenue: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    blppAccountMapping: '520010',
    account: '620030',
    accountDescription: 'External Charges Co-Management',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    blppAccountMapping: '520010',
    account: '620030',
    accountDescription: 'External Charges Co-Management',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    blppAccountMapping: '520030',
    account: '410040',
    accountDescription: 'Utilities - Water, Gas, Electricity',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    blppAccountMapping: '520030',
    account: '410040',
    accountDescription: 'Utilities - Water, Gas, Electricity',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2001',
    groupDescription: 'Maintenance Costs ',
    blppAccountMapping: '520040',
    account: '410030',
    accountDescription: 'Maintenance Contracts ',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true',
    subAccount: '4100301',
    subAccountDescription: 'Quarterly'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2001',
    groupDescription: 'Maintenance Costs ',
    blppAccountMapping: '520040',
    account: '410030',
    accountDescription: 'Maintenance Contracts ',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true',
    subAccount: '4100301',
    subAccountDescription: 'Quarterly'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    blppAccountMapping: '520050',
    account: '410000',
    accountDescription: 'Dispute Costs',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    blppAccountMapping: '520050',
    account: '410000',
    accountDescription: 'Dispute Costs',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    blppAccountMapping: '520060',
    account: '410070',
    accountDescription: 'Insurance (annual settlement)',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    blppAccountMapping: '520060',
    account: '410070',
    accountDescription: 'Insurance (annual settlement)',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '220',
    subCategoryDescription: 'Charges d\'impôts ',
    group: '2201',
    groupDescription: 'Taxes ',
    blppAccountMapping: '520070',
    account: '410010',
    accountDescription: 'Cantonal and communal Taxes'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '220',
    subCategoryDescription: 'Charges d\'impôts ',
    group: '2201',
    groupDescription: 'Taxes ',
    blppAccountMapping: '520070',
    account: '410010',
    accountDescription: 'Cantonal and communal Taxes'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    blppAccountMapping: '520080',
    account: '640020',
    accountDescription: 'Costs for New Rentals',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    blppAccountMapping: '520080',
    account: '640020',
    accountDescription: 'Costs for New Rentals',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '220',
    subCategoryDescription: 'Charges d\'impôts ',
    group: '2200',
    groupDescription: 'Property tax ',
    blppAccountMapping: '520090',
    account: '420000',
    accountDescription: 'Property tax'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '220',
    subCategoryDescription: 'Charges d\'impôts ',
    group: '2200',
    groupDescription: 'Property tax ',
    blppAccountMapping: '520090',
    account: '420000',
    accountDescription: 'Property tax'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    blppAccountMapping: '520100',
    account: '630010',
    accountDescription: 'Miscellaneous Costs ',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true',
    subAccount: '410050',
    subAccountDescription: 'TV Cable Costs'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    blppAccountMapping: '520100',
    account: '630010',
    accountDescription: 'Miscellaneous Costs ',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true',
    subAccount: '410050',
    subAccountDescription: 'TV Cable Costs'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    blppAccountMapping: '520110',
    account: '300200',
    accountDescription: 'Losses on Rentals',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    blppAccountMapping: '520110',
    account: '300200',
    accountDescription: 'Losses on Rentals',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2001',
    groupDescription: 'Maintenance Costs ',
    blppAccountMapping: '521010',
    account: '400000',
    accountDescription: 'Appartement Maintenance',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2001',
    groupDescription: 'Maintenance Costs ',
    blppAccountMapping: '521010',
    account: '400000',
    accountDescription: 'Appartement Maintenance',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2001',
    groupDescription: 'Maintenance Costs ',
    blppAccountMapping: '521020',
    account: '400100',
    accountDescription: 'Building Maintenance',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2001',
    groupDescription: 'Maintenance Costs ',
    blppAccountMapping: '521020',
    account: '400100',
    accountDescription: 'Building Maintenance',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    blppAccountMapping: '522010',
    account: '406000',
    accountDescription: 'Management fees',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true',
    accountIsManagementFee: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    blppAccountMapping: '522010',
    account: '406000',
    accountDescription: 'Management fees',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true',
    accountIsManagementFee: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '630010',
    accountDescription: 'Miscellaneous Costs ',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true',
    subAccount: '410100',
    subAccountDescription: 'Others'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2001',
    groupDescription: 'Maintenance Costs ',
    account: '410030',
    accountDescription: 'Maintenance Contracts ',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true',
    subAccount: '4100302',
    subAccountDescription: 'Biannual'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2001',
    groupDescription: 'Maintenance Costs ',
    account: '410030',
    accountDescription: 'Maintenance Contracts ',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true',
    subAccount: '4100303',
    subAccountDescription: 'Yearly'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '600040',
    accountDescription: 'Insurance (annual settlement)',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '501010',
    accountDescription: 'Insurance (annual settlement)',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '600050',
    accountDescription: 'Management fees',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true',
    accountIsManagementFee: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '600020',
    accountDescription: 'Petty Costs',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '620000',
    accountDescription: 'Fees on Works',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '640040',
    accountDescription: 'Miscellaneous Costs ',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '630000',
    accountDescription: 'Miscellaneous Costs ',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '630010',
    accountDescription: 'Miscellaneous Costs ',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '640000',
    accountDescription: 'Dispute Costs',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '410080',
    accountDescription: 'Costs for New Rentals',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '410060',
    accountDescription: 'Losses on Heating',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2001',
    groupDescription: 'Maintenance Costs ',
    account: '410030',
    accountDescription: 'Maintenance Contracts ',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2001',
    groupDescription: 'Maintenance Costs ',
    account: '600010',
    accountDescription: 'Maintenance Equipment/Material',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2001',
    groupDescription: 'Maintenance Costs ',
    account: '600000',
    accountDescription: 'Outside Amenities',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2001',
    groupDescription: 'Maintenance Costs ',
    account: '410020',
    accountDescription: 'Supplies for Caretaking',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '210',
    subCategoryDescription: 'CAPEX ',
    group: '2100',
    groupDescription: 'Capital Expenditure (CAPEX) ',
    account: '400300',
    accountDescription: 'Building Renovation',
    accountIsRenovationCost: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '210',
    subCategoryDescription: 'CAPEX ',
    group: '2100',
    groupDescription: 'Capital Expenditure (CAPEX) ',
    account: '400301',
    accountDescription: 'Building Renovation Fees',
    accountIsRenovationCost: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '210',
    subCategoryDescription: 'CAPEX ',
    group: '2100',
    groupDescription: 'Capital Expenditure (CAPEX) ',
    account: '400200',
    accountDescription: 'Appartement Renovation',
    accountIsRenovationCost: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '210',
    subCategoryDescription: 'CAPEX ',
    group: '2100',
    groupDescription: 'Capital Expenditure (CAPEX) ',
    account: '400201',
    accountDescription: 'Appartement Renovation Fees',
    accountIsRenovationCost: 'true'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '220',
    subCategoryDescription: 'Charges d\'impôts ',
    group: '2201',
    groupDescription: 'Taxes ',
    account: '501000',
    accountDescription: 'Direct Federal Tax'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '230',
    subCategoryDescription: 'Charges d\'administration ',
    group: '2300',
    groupDescription: 'Administration ',
    account: '610010',
    accountDescription: 'Auditor\'s Fees'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '230',
    subCategoryDescription: 'Charges d\'administration ',
    group: '2300',
    groupDescription: 'Administration ',
    account: '330000',
    accountDescription: 'Directors\' Fees'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '230',
    subCategoryDescription: 'Charges d\'administration ',
    group: '2300',
    groupDescription: 'Administration ',
    account: '640030',
    accountDescription: 'Directors\' Fees'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '250',
    subCategoryDescription: 'Autres charges financières ',
    group: '2500',
    groupDescription: 'Current Accounts ',
    account: '501020',
    accountDescription: 'Bank Fees'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '250',
    subCategoryDescription: 'Autres charges financières ',
    group: '2500',
    groupDescription: 'Current Accounts ',
    account: '620010',
    accountDescription: 'Bank Fees'
  },
  {
    clientId: 3,
    portfolioId: 1,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '250',
    subCategoryDescription: 'Autres charges financières ',
    group: '2500',
    groupDescription: 'Current Accounts ',
    account: '620040',
    accountDescription: 'Bank Fees'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '630010',
    accountDescription: 'Miscellaneous Costs ',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true',
    subAccount: '410100',
    subAccountDescription: 'Others'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2001',
    groupDescription: 'Maintenance Costs ',
    account: '410030',
    accountDescription: 'Maintenance Contracts ',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true',
    subAccount: '4100302',
    subAccountDescription: 'Biannual'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2001',
    groupDescription: 'Maintenance Costs ',
    account: '410030',
    accountDescription: 'Maintenance Contracts ',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true',
    subAccount: '4100303',
    subAccountDescription: 'Yearly'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '600040',
    accountDescription: 'Insurance (annual settlement)',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '501010',
    accountDescription: 'Insurance (annual settlement)',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '600050',
    accountDescription: 'Management fees',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true',
    accountIsManagementFee: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '600020',
    accountDescription: 'Petty Costs',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '620000',
    accountDescription: 'Fees on Works',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '640040',
    accountDescription: 'Miscellaneous Costs ',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '630000',
    accountDescription: 'Miscellaneous Costs ',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '630010',
    accountDescription: 'Miscellaneous Costs ',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '640000',
    accountDescription: 'Dispute Costs',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '410080',
    accountDescription: 'Costs for New Rentals',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2000',
    groupDescription: 'Current Expenses ',
    account: '410060',
    accountDescription: 'Losses on Heating',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2001',
    groupDescription: 'Maintenance Costs ',
    account: '410030',
    accountDescription: 'Maintenance Contracts ',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2001',
    groupDescription: 'Maintenance Costs ',
    account: '600010',
    accountDescription: 'Maintenance Equipment/Material',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2001',
    groupDescription: 'Maintenance Costs ',
    account: '600000',
    accountDescription: 'Outside Amenities',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '200',
    subCategoryDescription: 'OPEX',
    group: '2001',
    groupDescription: 'Maintenance Costs ',
    account: '410020',
    accountDescription: 'Supplies for Caretaking',
    accountIsPmVisible: 'true',
    accountIsOpex: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '210',
    subCategoryDescription: 'CAPEX ',
    group: '2100',
    groupDescription: 'Capital Expenditure (CAPEX) ',
    account: '400300',
    accountDescription: 'Building Renovation',
    accountIsRenovationCost: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '210',
    subCategoryDescription: 'CAPEX ',
    group: '2100',
    groupDescription: 'Capital Expenditure (CAPEX) ',
    account: '400301',
    accountDescription: 'Building Renovation Fees',
    accountIsRenovationCost: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '210',
    subCategoryDescription: 'CAPEX ',
    group: '2100',
    groupDescription: 'Capital Expenditure (CAPEX) ',
    account: '400200',
    accountDescription: 'Appartement Renovation',
    accountIsRenovationCost: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '210',
    subCategoryDescription: 'CAPEX ',
    group: '2100',
    groupDescription: 'Capital Expenditure (CAPEX) ',
    account: '400201',
    accountDescription: 'Appartement Renovation Fees',
    accountIsRenovationCost: 'true'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '220',
    subCategoryDescription: 'Charges d\'impôts ',
    group: '2201',
    groupDescription: 'Taxes ',
    account: '501000',
    accountDescription: 'Direct Federal Tax'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '230',
    subCategoryDescription: 'Charges d\'administration ',
    group: '2300',
    groupDescription: 'Administration ',
    account: '610010',
    accountDescription: 'Auditor\'s Fees'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '230',
    subCategoryDescription: 'Charges d\'administration ',
    group: '2300',
    groupDescription: 'Administration ',
    account: '330000',
    accountDescription: 'Directors\' Fees'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '230',
    subCategoryDescription: 'Charges d\'administration ',
    group: '2300',
    groupDescription: 'Administration ',
    account: '640030',
    accountDescription: 'Directors\' Fees'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '250',
    subCategoryDescription: 'Autres charges financières ',
    group: '2500',
    groupDescription: 'Current Accounts ',
    account: '501020',
    accountDescription: 'Bank Fees'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '250',
    subCategoryDescription: 'Autres charges financières ',
    group: '2500',
    groupDescription: 'Current Accounts ',
    account: '620010',
    accountDescription: 'Bank Fees'
  },
  {
    clientId: 4,
    portfolioId: 2,
    accountingPlan: 'Budget',
    category: '2',
    categoryDescription: 'Charge',
    subCategory: '250',
    subCategoryDescription: 'Autres charges financières ',
    group: '2500',
    groupDescription: 'Current Accounts ',
    account: '620040',
    accountDescription: 'Bank Fees'
  }
];
