import { APP_INITIALIZER, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

import { MainLayoutComponent } from './main-layout.component';
import { SidenavComponent } from './sidenav/sidenav.component';
import { HeaderComponent } from './header/header.component';

import { KeycloakAngularModule, KeycloakService } from 'keycloak-angular';
import { BrowserModule } from '@angular/platform-browser';


// tslint:disable-next-line:typedef
function initializeKeycloak(keycloak: KeycloakService) {
  return () =>
    keycloak.init({
      config: {
        realm: 'New STREETS',
        url: 'https://openid.xtech.io/auth',
        clientId: 'iccube-dev'
      },
      bearerExcludedUrls: ['/assets', '/clients/public'],
      initOptions: {
        token: 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIzNFh1S1JvdHlERXhKcFQ5Y0pHeU45dFhFbFJMbERTLU9fR3JWZVdEU0dBIn0.eyJqdGkiOiJlNGQzZDIzYS00M2RmLTQwZmUtYTAwYS1jNjM4NzJlN2VjNzQiLCJleHAiOjE2MDIyNDc2MDksIm5iZiI6MCwiaWF0IjoxNjAyMjQ3MzA5LCJpc3MiOiJodHRwczovL29wZW5pZC54dGVjaC5pby9hdXRoL3JlYWxtcy9OZXclMjBTVFJFRVRTIiwiYXVkIjpbImljY3ViZS1wcm9kIiwiYWNjb3VudCIsImljY3ViZS11YXQiXSwic3ViIjoiNGI3MGJmNzUtNDY2Zi00MTdkLTk0NTgtZGFjMWQ2NDZmYjQxIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiaWNjdWJlLWRldiIsIm5vbmNlIjoiMzAyZTQ3MTQtYWMxZC00YzVhLWFkYmQtMWYzZjYwMzFiZjAyIiwiYXV0aF90aW1lIjoxNjAyMjQzNTMxLCJzZXNzaW9uX3N0YXRlIjoiMTliYzdiOGItOTFiNy00ZjIwLTgyZTAtZmU3MDhlY2NiZDUzIiwiYWNyIjoiMCIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJJQzNfQUNUT1JfQ09NVU5VUyIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJJQzNfQUNMX0RBU0hCT0FSRFNfU0VUXzAxIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiaWNjdWJlLWRldiI6eyJyb2xlcyI6WyJJQzNfREFUQV9ERVYiXX0sImljY3ViZS1wcm9kIjp7InJvbGVzIjpbIklDM19EQVRBX1BST0QiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfSwiaWNjdWJlLXVhdCI6eyJyb2xlcyI6WyJJQzNfREFUQV9VQVQiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJJQ0NVQkUgVEVTVCIsInByZWZlcnJlZF91c2VybmFtZSI6ImljY3ViZV90ZXN0IiwiZ2l2ZW5fbmFtZSI6IklDQ1VCRSIsImZhbWlseV9uYW1lIjoiVEVTVCJ9.QtPNASEAFNvVVWTro2fDM5Tbz5dBNYmPbQicmoMaJs8yi6KbEyQNWAKSCWw54TXJVkaiM3ZLiIdfAmjYpmkPtJ9mIv-pkVNoZ8rz1M2LIrv-dQFUAoTm8IGdkfSN-nnMwPrO76nkIYonM2Hql6jj2rWnsILqf7LlXB4MXkInGTuRya0wlJpkFwBjxg9XSnzOUpnfU1cmTK5M1rQHwrzIzhgdEz9IJGK1S-nzD9I-JspW2mG8pSClFGt64yPbO2hCwFR1bWljzI7p9JPR-ki8j4e5Xo7oAQhoWkD6_hu4eS8PNTS9Lo8Z4DecCaPXibEXhnVXHSxnJIdkI1jRrYyPSw',
        refreshToken: 'eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI1NTkzNjhhOS0yZGJiLTQ5ZjQtYTA3Zi05OWVlOGJkNzM0ZjIifQ.eyJqdGkiOiJkZTIzOTIwMy1mMWEzLTRiZTgtODlkOS1hZmNiMzZiZTMzYjQiLCJleHAiOjE2MDIyNjE3MDksIm5iZiI6MCwiaWF0IjoxNjAyMjQ3MzA5LCJpc3MiOiJodHRwczovL29wZW5pZC54dGVjaC5pby9hdXRoL3JlYWxtcy9OZXclMjBTVFJFRVRTIiwiYXVkIjoiaHR0cHM6Ly9vcGVuaWQueHRlY2guaW8vYXV0aC9yZWFsbXMvTmV3JTIwU1RSRUVUUyIsInN1YiI6IjRiNzBiZjc1LTQ2NmYtNDE3ZC05NDU4LWRhYzFkNjQ2ZmI0MSIsInR5cCI6IlJlZnJlc2giLCJhenAiOiJpY2N1YmUtZGV2Iiwibm9uY2UiOiIzMDJlNDcxNC1hYzFkLTRjNWEtYWRiZC0xZjNmNjAzMWJmMDIiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiIxOWJjN2I4Yi05MWI3LTRmMjAtODJlMC1mZTcwOGVjY2JkNTMiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiSUMzX0FDVE9SX0NPTVVOVVMiLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIiwiSUMzX0FDTF9EQVNIQk9BUkRTX1NFVF8wMSJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImljY3ViZS1kZXYiOnsicm9sZXMiOlsiSUMzX0RBVEFfREVWIl19LCJpY2N1YmUtcHJvZCI6eyJyb2xlcyI6WyJJQzNfREFUQV9QUk9EIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX0sImljY3ViZS11YXQiOnsicm9sZXMiOlsiSUMzX0RBVEFfVUFUIl19fSwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSJ9.YQv1669j4SufaTS1uL8nZ9K0Jx52hElvZtgVvam6nxk',
        idToken: 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIzNFh1S1JvdHlERXhKcFQ5Y0pHeU45dFhFbFJMbERTLU9fR3JWZVdEU0dBIn0.eyJqdGkiOiI3Mjk2ODg1OC0xZGQ0LTQ0ODMtOThiYi0xM2UzZTIzMGYwY2YiLCJleHAiOjE2MDIyNDc2MDksIm5iZiI6MCwiaWF0IjoxNjAyMjQ3MzA5LCJpc3MiOiJodHRwczovL29wZW5pZC54dGVjaC5pby9hdXRoL3JlYWxtcy9OZXclMjBTVFJFRVRTIiwiYXVkIjoiaWNjdWJlLWRldiIsInN1YiI6IjRiNzBiZjc1LTQ2NmYtNDE3ZC05NDU4LWRhYzFkNjQ2ZmI0MSIsInR5cCI6IklEIiwiYXpwIjoiaWNjdWJlLWRldiIsIm5vbmNlIjoiMzAyZTQ3MTQtYWMxZC00YzVhLWFkYmQtMWYzZjYwMzFiZjAyIiwiYXV0aF90aW1lIjoxNjAyMjQzNTMxLCJzZXNzaW9uX3N0YXRlIjoiMTliYzdiOGItOTFiNy00ZjIwLTgyZTAtZmU3MDhlY2NiZDUzIiwiYWNyIjoiMCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiSUNDVUJFIFRFU1QiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJpY2N1YmVfdGVzdCIsImdpdmVuX25hbWUiOiJJQ0NVQkUiLCJmYW1pbHlfbmFtZSI6IlRFU1QifQ.Ff_gltbnWBc9B-3dHHoMPu7zdtYH6b0b5MY3hAjcVwPV1pmzIOQ3G-I5jdsm83ihGGH0XdT2ioO-M_11utU9ZPUzsVkQ6IGzwFNBsJH2GIr-sCgl3dj_NMGl4YjCVV-EDfgSQZrfYMD8lo1PU49jOizx8-rztzuejWq0EuO9zYW3LlEmwTlFadt_w6WtW50uX0LleiBG2OoPC07rsruWhrEoXQijPzMmNYzHDs9a0mKCNBCtDehiaBsvxpU1CmLGs77-BMHWNqVrudHK9FLZVB2jdhF-rnAoZlcR8oxBbl6ubt4CjTSCmSBywro5rk6KXeK013WEWwL8XtysHFoyLg',
        onLoad: 'check-sso',
        silentCheckSsoRedirectUri:
          window.location.origin + '/assets/silent-check-sso.html',
      }
    });
}

@NgModule({
  declarations: [MainLayoutComponent, SidenavComponent, HeaderComponent],
  imports: [CommonModule, RouterModule, BrowserModule, KeycloakAngularModule],
  providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: initializeKeycloak,
      multi: true,
      deps: [KeycloakService],
    },
  ]
})
export class MainLayoutModule { }
